### ISSUE TITLE
Zebra doesn't see it

### ISSUE THREAD

**Issue by LevRost2306** [UInt2048/OpenPlistBuddy#1]
Either I install it with Sileo or Zebra, Zebra doesn't see a tweak, but Sileo does. So, when I install Jetsam then (with Sileo, cause Zebra doesn't see plistbuddy and so doesn't allow me to install jetsam), I don't know does it work (there was no message after installation).
iPad Air 1, arm64

**Comment by UInt2048** [comment]
Install OpenPlistBuddy from [the releases](https://github.com/UInt2048/OpenPlistBuddy/releases/latest) first then refresh Zebra's sources.

**Comment by UInt2048** [comment]
If you're using Sileo, I believe you need to click "view details" to see the actual log being emitted when installing.

**Comment by LevRost2306** [comment]
> Install OpenPlistBuddy from [the releases](https://github.com/UInt2048/OpenPlistBuddy/releases/latest) first then refresh Zebra's sources.

THANKS, refreshing zebra sources helped
